In [1]:
# 2. Numpy
# Using NumPy create random vector of size 20 having only float in the range 1-20.
# Then reshape the array to 4 by 5
# Then replace the max in each row by 0 (axis=1)
# (you can NOT implement it via for loop)

import numpy as np

# Create random vector of size 20 with floats between 1 and 20
vec = np.random.uniform(1, 20, 20)

# Reshape the vector to 4 by 5
mat = vec.reshape(4, 5)

# Replace the max in each row by 0
mat[np.arange(4), mat.argmax(axis=1)] = 0

# Print output
print(mat)

[[ 9.95854166  4.24025084  9.27866648  0.         10.87486538]
 [ 6.58887941  9.08720709  0.          3.67671123 13.65612451]
 [18.14986991 16.89837327  8.1228144  11.86297309  0.        ]
 [ 0.          2.9089018  16.79040963  3.55358712 14.12544798]]
